import test from 'node:test';import assert from 'node:assert/strict';import {handleApi} from './server/api.mjs';import {ADMIN_OWNER} from './server/billing.mjs';import {localDatabase} from './local-db.mjs';
async function call(db,user,path,data){const r=await handleApi(new Request('https://test.example'+path,{method:data?'POST':'GET',headers:{'oai-authenticated-user-id':user,'oai-authenticated-user-email':'client@example.test',origin:'https://test.example','content-type':'application/json'},body:data?JSON.stringify(data):undefined}),{DB:db});return {status:r.status,data:await r.json()};}
test('Cliente não libera o próprio acesso e pagamento não é inferido pelo cadastro',async()=>{const db=localDatabase();try{let status=await call(db,'client','/api/billing');assert.equal(status.data.price,990);assert.equal(status.data.active,false);assert.equal(status.data.checkoutUrl,'');assert.equal((await call(db,'client','/api/company',{name:'Cliente',opening:0,openingDate:'2026-01-01'})).status,402);await call(db,'client','/api/billing/join',{name:'Cliente',validUntil:'2100-01-01',admin:true});assert.equal((await call(db,'client','/api/billing')).data.active,false);assert.equal((await call(db,'client','/api/admin/members')).status,403);assert.equal((await call(db,ADMIN_OWNER,'/api/billing')).data.active,true);
 const grant={userId:'client',revision:0,validUntil:'2027-01-01',reason:'Pagamento conferido',paymentRef:'MP-TEST-1'};
 assert.equal((await call(db,ADMIN_OWNER,'/api/admin/access',grant)).status,200);assert.equal((await call(db,ADMIN_OWNER,'/api/admin/access',grant)).status,409);assert.equal((await call(db,'client','/api/billing')).data.active,true);assert.equal(db.sqlite.prepare('SELECT count(*) n FROM membership_events').get().n,1);
 assert.equal((await call(db,'client','/api/company',{name:'Cliente',opening:0,openingDate:'2026-01-01'})).status,201);
 db.sqlite.prepare("UPDATE members SET valid_until='2000-01-01' WHERE user_id='client'").run();assert.equal((await call(db,'client','/api/state')).status,200);assert.equal((await call(db,'client','/api/profile',{name:'Novo',profileType:'pf'})).status,402);
 }finally{db.sqlite.close();}});
test('Link restrito ao checkout de assinatura e auditoria atômica',async()=>{const db=localDatabase();try{assert.equal((await call(db,ADMIN_OWNER,'/api/admin/settings',{checkoutUrl:'https://evil.example',supportEmail:'support@example.test'})).status,400);assert.equal((await call(db,ADMIN_OWNER,'/api/admin/settings',{checkoutUrl:'https://www.mercadopago.com.br/subscriptions/checkout?preapproval_plan_id=12345678901234567890123456789012',supportEmail:'support@example.test'})).status,200);await call(db,'client','/api/billing/join',{name:'Cliente'});db.sqlite.exec("CREATE TRIGGER audit_fail BEFORE INSERT ON membership_events BEGIN SELECT RAISE(ABORT,'failure'); END");assert.equal((await call(db,ADMIN_OWNER,'/api/admin/access',{userId:'client',revision:0,validUntil:'2027-01-01',reason:'Teste',paymentRef:'MP-TEST'})).status,503);assert.equal((await call(db,'client','/api/billing')).data.active,false);}finally{db.sqlite.close();}});
