import test from 'node:test';import assert from 'node:assert/strict';import {validateInvestment,calculateInvestment} from './public/investments.mjs';import {localDatabase} from './local-db.mjs';import {handleApi} from './server/api.mjs';
const sample=()=>({name:'Tesouro teste',kind:'Tesouro Prefixado',principal:100000,start:'2026-01-01',end:'2027-01-01',exitDate:'2026-01-11',model:'fixed',tax:'regressive',rate:14.5,percent:100,spread:0,endGross:null,exitGross:101000,endFees:200,exitFees:0,endTax:0,exitTax:0,rateDate:''});
test('Rendimento composto, IR, taxas e cotação de resgate independentes',()=>{const d=validateInvestment(sample()),end=calculateInvestment(d,'end'),exit=calculateInvestment(d,'exit');assert.equal(end.gross,114500);assert.equal(end.ir,2538);assert.equal(end.net,111762);assert.equal(exit.iof,660);assert.equal(exit.ir,77);assert.equal(exit.net,100263);assert.equal(calculateInvestment({...d,exitGross:null},'exit'),null);assert.equal(calculateInvestment({...d,exitGross:90000},'exit').ir,0);});
test('Limites regressivos, IOF 30 dias, CDI 100% e modo manual',()=>{const d=sample();for(const [days,rate] of [[180,22.5],[181,20],[360,20],[361,17.5],[720,17.5],[721,15]]){const date=new Date(Date.parse(d.start)+days*86400000).toISOString().slice(0,10);assert.equal(calculateInvestment({...d,end:date},'end').irRate,rate);}assert.equal(calculateInvestment({...d,exitDate:'2026-01-31'},'exit').iof,0);assert.equal(calculateInvestment({...d,model:'cdi'},'end').gross,114500);assert.equal(calculateInvestment({...d,model:'manual',tax:'manual',endGross:120000,endTax:3000,endFees:200},'end').net,116800);assert.throws(()=>validateInvestment({...d,end:'2023-01-01'}));});
async function call(db,user,path,data){// Existing financial tests use explicitly provisioned local memberships. Billing authorization has separate tests.
 if(path==='/api/company'&&db?.sqlite)db.sqlite.prepare("INSERT OR IGNORE INTO members (user_id,email,name,valid_until,requested_at,updated_at) VALUES (?,?,?,'2100-12-31','2026-01-01','2026-01-01')").run(user,'test@example.test',user);
const headers={'oai-authenticated-user-id':user,origin:'https://test.example','content-type':'application/json'};const r=await handleApi(new Request('https://test.example'+path,{headers,method:data?'POST':'GET',body:data?JSON.stringify(data):undefined}),{DB:db});return {status:r.status,data:await r.json()};}
test('Investimentos persistem, edição controla revisão e outro usuário não acessa',async()=>{const db=localDatabase();try{for(const u of ['a','b'])await call(db,u,'/api/company',{name:u,profileType:'pf',opening:0,openingDate:'2026-01-01'});const data={...sample(),id:crypto.randomUUID(),revision:0};assert.equal((await call(db,'a','/api/investments',data)).status,201);assert.equal((await call(db,'a','/api/investments',data)).status,200);assert.equal((await call(db,'b','/api/investments')).data.investments.length,0);assert.equal((await call(db,'b','/api/investments',data)).status,409);const update={...data,revision:1,principal:200000};assert.equal((await call(db,'a','/api/investments',update)).status,200);assert.equal((await call(db,'a','/api/investments',{...data,principal:300000})).status,409);assert.equal((await call(db,'a','/api/investments')).data.investments[0].principal,200000);assert.equal((await call(db,'a','/api/state')).data.rows.length,0);}finally{db.sqlite.close();}});
test('Busca de taxa usa somente série permitida e responde a indisponibilidade',async()=>{const db=localDatabase(),original=globalThis.fetch;try{await call(db,'a','/api/company',{name:'a',profileType:'pf',opening:0,openingDate:'2026-01-01'});globalThis.fetch=async url=>{assert.match(url,/bcdata.sgs.4389/);return Response.json([{data:'10/09/2026',valor:'13.90'}]);};assert.equal((await call(db,'a','/api/investment-rate?model=cdi')).data.rate,13.9);assert.equal((await call(db,'a','/api/investment-rate?model=invalid')).status,400);globalThis.fetch=async()=>{throw Error('offline')};assert.equal((await call(db,'a','/api/investment-rate?model=selic')).status,503);}finally{globalThis.fetch=original;db.sqlite.close();}});
